<?php
/**
 * Copyright (c) 山东六牛网络科技有限公司 https://liuniukeji.com
 *
 * @Description    Index 控制器逻辑
 * @Author         王春志 QQ:1523494386
 * @Copyright      Copyright (c) 山东六牛网络科技有限公司 保留所有版权(https://www.liuniukeji.com)
 * @Date           2020/5/18 0018 10:59
 * @CreateBy       PhpStorm
 */

namespace app\logic\controller;
use app\common\controller\Logic;

class Index extends Logic
{
    /**
     * 无需登录的方法,同时也就不需要鉴权了
     * @var array
     */
    protected $noNeedLogin = ['*'];

    /**
     * 无需鉴权的方法,但需要登录
     * @var array
     */
    protected $noNeedRight = ['*'];

    protected static $rotationChartModel = null;


    /**
     * 初始化
     * User: 王春志
     * Date: 2020/5/18 0018  11:26
     */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub


    }


}
